before_script:
  - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
  - dpkg -i erlang-solutions_1.0_all.deb
  - apt-get update
  - apt-get -y install elixir
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix deps.compile

test:
  stage: test
  script:
    - mix test
  only:
    - master
