image: trenpixster/elixir
service: rabbitmq
before_script:
  - service rabbitmq-server start
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix deps.compile

test:
  stage: test
  script:
    - mix test
  only:
    - master
