image: trenpixster/elixir
services:
  - rabbitmq:latest
variables:
  RABBITMQ_DEFAULT_USER: user
  RABBITMQ_DEFAULT_PASS: password
  MIX_ENV: test
before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix deps.compile

test:
  stage: test
  script:
    - mix test
  only:
    - master
